# Generated by Django 4.2.2 on 2023-09-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumeimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='store'),
        ),
    ]
