# Generated by Django 4.2.2 on 2023-07-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='perfume',
            options={'ordering': ['price']},
        ),
    ]
