# Generated by Django 4.2.2 on 2023-07-18 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_perfume_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
