# Generated by Django 4.2.2 on 2023-06-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_product_orderitem_perfume'),
        ('store', '0002_cart_review_productimage_category_cartitems_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Perfume',
        ),
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='PerfumeImage',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='product',
            new_name='perfume',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='perfume',
        ),
    ]
