# Generated by Django 4.2.2 on 2023-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_perfume_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
