# Generated by Django 4.2.2 on 2023-06-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_perfume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfumeimage',
            old_name='product',
            new_name='perfume',
        ),
    ]
