# Generated by Django 4.2.2 on 2023-07-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_perfumeimage_perfume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='customer_name',
        ),
    ]
